### ISSUE TITLE
Notifications not received when app is closed (Android)

### ISSUE THREAD

**Issue by Leftyx** [one-signal/OneSignal-Cordova-SDK#1]
I've upgraded today from ver. 1.5 and things are not working as expected. 
With ver. 1.5 I can receive notifications when my app is running (through didReceiveRemoteNotificationCallBack) and in the notification drawer when the app is closed.

After the upgrade to ver. 1.6 things are not working anymore. 
I can only receive notifications when my app is running and now the notifications are show in the drawer (good thing).

**Comment by jkasten2** [comment]
Sorry about the issue, it is now fixed in version 1.6.1. It should now be available on the Cordova plugin registry and PhoneGap Build.

Thanks.
