### ISSUE TITLE
notificationOpenedCallback called again after pause

### ISSUE THREAD

**Issue by chcnetconsulting** [one-signal/OneSignal-Cordova-SDK#10]
Hello all together,

I have encountered a strange problem, that occurs only, if I need to launch an external web browser (not the internal one).
Doing so, ALTHOUGH the callback is finished for sure, at least in javascript, sends the app to the background (sofar so god). I did this to open the app store (to explain, why).
After returning to the app, the callback function is called with the exact same message data again, so my messge box is displayed again.

Obviously this callback should be called only once

**Comment by jkasten2** [comment]
Hello,

I am not able to reproduce an issue with the notificationOpenedCallback firing more than once when opening a notification with a launch URL set.

Could you let us know the following:
- Cordova version (run `cordova -version`)
- OneSignal version (run 'cordova plugin list`)
- Mobile OS and version your testing on.
- Exact steps used to reproduce the issue.

Thanks.

**Comment by jkasten2** [comment]
Could you let us know the details listed above?

Also if you can create an example project reproducing we can quickly come up with a fix.

Thanks.

**Comment by jkasten2** [comment]
Was able to reproduce the issue on iOS and fix the issue in commit d0701fbb686cb53a1640866cc8dabea075a0098f.

Released version 1.9.1 with this fix included and its live on npmjs.

Thanks.
