### ISSUE TITLE
OneSignal plugin + Cordova Push Plugin

### ISSUE THREAD

**Issue by murliatdure** [one-signal/OneSignal-Cordova-SDK#11]
Can we have the Cordova Push Plugin and also the OneSignal Push plugin both at the same time in one application?

**Comment by jkasten2** [comment]
Are you referring to [phonegap/phonegap-plugin-push](https://github.com/phonegap/phonegap-plugin-push)? If so you will see the following error if your building for Android.
```
com.android.dex.DexException: Multiple dex files define Landroid/support/annotation/AnimRes;
```

There is a incompatibility issue with phonegap-plugin-push and any other plugins that also use an Android Support Library version (like OneSignal). However they just fix it with commit phonegap/phonegap-plugin-push@6b5bebb85c94cca0a734c743b37a50fccc57c8c7. This commit hasn't been added to a release yet but you can add the head version (not well test) by running the following:
```
cordova plugin remove phonegap-plugin-push
cordova plugin add https://github.com/phonegap/phonegap-plugin-push
```

Thanks.

**Comment by jkasten2** [comment]
The above work around for Android is no longer needed when using phonegap-plugin-push with the OneSignal plugin (onsignal-cordova-plugin). phonegap-plugin-push has been released with the commit noted above.

Please reopen this issue with more details if you're still seeing a conflict.

Thanks.
