### ISSUE TITLE
Phonegap Build Release

### ISSUE THREAD

**Issue by murliatdure** [one-signal/OneSignal-Cordova-SDK#13]
com.onesignal.plugins.onesignal   	pgb	1.9.0	1.9.0	android,ios
![image](https://cloud.githubusercontent.com/assets/7137859/9981496/a66027fe-5fdc-11e5-942f-19e74c15ab17.png)

After building the app, I can see I get only 1.9.0 release only.
Also It doesn't get added for WIN support

Can you please assist if anything special is required for handling the same.

**Comment by murliatdure** [comment]
I forced to put the same on 1.9.1 - It fails.

![image](https://cloud.githubusercontent.com/assets/7137859/9981548/21a20a12-5fde-11e5-89ed-40b8d38ee52b.png)

**Comment by jkasten2** [comment]
PhoneGap Build has [deprecated their own plugin directory](http://phonegap.com/blog/2015/09/04/public-plugin-deprecation-on-build/) in favor of npmsj and plugin developers can no longer update their plugins. We have mark our plugin deprecated pointing to our npmjs plugin `onesignal-cordova-plugin-pgb-compat`. Please replace the following in your `config.xml`:
```xml
<gap:plugin name="com.onesignal.plugins.onesignal" />
```
WITH:
```xml
<gap:plugin name="onesignal-cordova-plugin-pgb-compat" source="npm" />
<gap:plugin name="cordova-plugin-googleplayservices" source="npm" />
<gap:plugin name="cordova-plugin-android-support-v4" source="npm" />
```

If all other developers using Cordova, PhoneGap CLI, Ionic, etc use `onesignal-cordova-plugin` instead.

Thanks.
