### ISSUE TITLE
Open Specific View when Opening App from Notification

### ISSUE THREAD

**Issue by softBarbarian** [one-signal/OneSignal-Cordova-SDK#21]
Is there a way to Open Specific View when Opening App from Notification?

Thanks a lot

**Comment by jaapjanfrans** [comment]
Yes there is. When composing a push notification (either through the onesignal backend UI or using the server rest API) you can add additional data to the notification in key/value pairs. When your cordova app receives a notification, this additional data of the notification can be read from the JSON object in the callback function (see https://documentation.onesignal.com/docs/phonegap--cordova-sdk-api#notificationOpenedCallback)

For example, you could add a key 'view' with value 'dashboard' to a notification, and in the function handling the notification in your app check the JSON object for a 'view' key in the additional data and send the user to the dashboard view if the value equals 'dashboard'.

**Comment by softBarbarian** [comment]
@jaapjanfrans thanks a lot, closing this

**Comment by ahmedalmulki** [comment]
Hi @jaapjanfrans  I want the same thing but the link you send it before is not working anymore, can u give some example to work on it please .
