### ISSUE TITLE
Double push

### ISSUE THREAD

**Issue by vespino** [one-signal/OneSignal-Cordova-SDK#22]
I'm using the following code:

```
    didReceiveRemoteNotificationCallBack : function(jsonData) {
		//set redirect
		if(jsonData.additionalData.page) {
			redirect=jsonData.additionalData.page;
			title=jsonData.additionalData.title;
			label1=jsonData.additionalData.label1;
			label2=jsonData.additionalData.label2;

			//slug
			slug=getParameter('slug', redirect);
		}

		check();

		if(jsonData.isActive===true) {
			if(redirect && label1 && label2) {
				navigator.notification.confirm(
					jsonData.message,
					function(button) {
						if(button==1) {
							$.mobile.changePage(redirect, { transition: 'slide' });
						}
					},
					title,
					[label1,label2]
				);
			}else navigator.notification.alert(jsonData.message, nothing, 'Pannenkoekenhuizen', 'Sluiten');
		}else $.mobile.changePage(redirect, { transition: 'slide' });
    }
```

When sending a push message and clicking on it from the notifications bar the apps opens, redirect, so that works perfectly. When going to another page within the app, the action after "if(jsonData.isActive===true) {" is triggered so the message is shown twice.

jsonData.isActive is used when the app is on foreground when receiving the message right?

I'm I doing something wrong?

**Comment by jkasten2** [comment]
This sounds like an iOS bug we fixed in [version 1.9.1](https://github.com/one-signal/OneSignal-Cordova-SDK/releases/tag/1.9.1). Can you verify you have the lastest version?

Thanks.

**Comment by vespino** [comment]
I have the latest version, but I'm testing on Android ;)

**Comment by vespino** [comment]
Any news on this issue?

**Comment by jkasten2** [comment]
Sorry about the delay, I am making a number of changes to our Android native code that may effect this bug. I'll make sure to test that the changes fixes this issue when put the new jar into our Cordova plugin.

Thanks.

**Comment by vespino** [comment]
Great job! I'm looking forward to it and would gladly test it for you.

**Comment by vespino** [comment]
Any news on this issue?

**Comment by jkasten2** [comment]
Sorry about the delay, version 1.10.0 of our SDK should fix this issue. Let us know if you're still seeing an issue or if this version fixes it for you.

**Comment by vespino** [comment]
Testing now. I see I have to use "onesignal-cordova-plugin" instead of "onesignal-cordova-plugin-pgb-compat" for use with PGB, correct?

What about these plugins, are these still needed?

cordova-plugin-googleplayservices
cordova-plugin-android-support-v4

**Comment by vespino** [comment]
When using "onesignal-cordova-plugin" with PGB build fails. :(

"onesignal-cordova-plugin-pgb-compat" still works but uses an older version (1.9.1).

Help?

**Comment by jkasten2** [comment]
Please use the following `config.xml` settings to use `onesignal-cordova-plugin` per our [PhoneGap Build (PGB) setup documentation](https://documentation.onesignal.com/docs/phonegap-sdk-installation).
```xml
<gap:plugin name="onesignal-cordova-plugin" source="npm" />

<!-- Recommend the newest cli but requires cli-5.1.1+, and gradle for Android. -->
<!-- If the below setting are not compatible with your project set the "PGB ANT" version above. -->
<preference name="phonegap-version" value="cli-5.2.0" />
<preference name="android-build-tool" value="gradle" />
```

For `onesignal-cordova-plugin` to work you will need to remove the following from your project:
* `cordova-plugin-googleplayservices`
* `cordova-plugin-android-support-v4`

If you still see build errors please review our [OneSignal Compatibility With Other PhoneGap Build(BGP) Android Plugins](https://documentation.onesignal.com/docs/cordova-common-problems#onesignal-compatibility-with-other-phonegap-buildb) section to update your old plugins to their newer more compatible versions.

If all else fails you can still use `onesignal-cordova-plugin-pgb-compat`. It was updated to 1.10.1 at the same time the main branch was.

Thanks.

**Comment by vespino** [comment]
Great job, everything seems to work fine now!
