### ISSUE TITLE
Building problem on Windows 8.1

### ISSUE THREAD

**Issue by Omnem** [one-signal/OneSignal-Cordova-SDK#23]
After adding the oneSignal plugin to the windows version of the app and trying to run the app:

```
cordova plugin add onesignal-cordova-plugin
cordova run windows
```

I'm getting the following error:

```
C:\Program Files (x86)\MSBuild\Microsoft\NuGet\Microsoft.NuGet.targets(181,5):
error : Couldn't find the required information in the lock file. Make sure you
have .NETCore,Version=v5.0/win10-anycpu mentioned in your targets. [D:\xampp\ht
docs\**\platforms\windows\CordovaApp.Windows10.jsproj]

ERROR: Error code 1 for command: C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild with args: D:\xampp\htdocs\**\platforms\windows\CordovaApp.Windows10.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=debug,/p:Platform=anycpu
ERROR running one or more of the platforms: Error: cmd: Command failed with exit code 2
You may not have the required environment or OS to run this project
```

Line 181 seems to be:

```
<ResolveNuGetPackageAssets Condition="Exists('$(FrameworkInjectionLockFile)')"
                               NuGetPackagesDirectory="$(FrameworkInjectionPackagesDirectory)"
                               RuntimeIdentifier="$(NuGetRuntimeIdentifier)"
                               TargetMonikers="$(NuGetTargetMonikerToInject)"
                               ProjectLockFile="$(FrameworkInjectionLockFile)">
<Output TaskParameter="ResolvedCopyLocalItems" ItemName="_InjectNetCoreFrameworkPayload" />
    </ResolveNuGetPackageAssets>
```

It works if I remove the plugin. 
Any thoughts ?

P.S.
I'm using Windows 10 as operating system, cordova version 5.3.3 and Visual Studio Community 2015.

**Comment by jkasten2** [comment]
I ran the following on my Windows 10 system without an issue getting the project to run.

```
cordova create OneSignal-Win-Test
cd OneSignal-Win-Test
cordova plugin add onesignal-cordova-plugin
cordova platform add windows
cordova run windows
```

I also have Visual Studio Community 2015 and version 14 of MSBuild tools was used on my system shown in the output.

Note that the OneSignal Cordova plugin only works for Windows Phone 8.1 push notifications but should not interfere with Windows desktop builds. Push for Windows Desktop support is something we plan on adding in the future.

Thanks.

**Comment by Omnem** [comment]
Thanks for your reply, I wasn't aware it didn't work yet with Windows Desktop. 
I tried to get it to work more today to no avail.
Adding onesignal to a blank project seems to build correctly. Just not on my existing poject. 

 I'll return to it later. Thanks.

**Comment by DaniloCouto** [comment]
I've been experiencing a similar error on my project.
But I'm developing on Ionic Framework.
Pure cordova projects runs great with Onesignal Plugin , but ionic projects doesn't run. It just exit with code 0 after deploy and before loading onesignal plugin.
I use [winstore jscompat](https://github.com/MSOpenTech/winstore-jscompat) to run Ionic/AngularJS code on Windows Phone. I don't know if angular or this winstore-jscompat;lib can interfere with onesignal code... but it's strange.

**Comment by jkasten2** [comment]
@DaniloCouto I am not able to reproduce an issue with OneSignal and Ionic when building and running Windows Phone 8.1 on a new project. Keep in mind `alert` is not defined for WP8.1 and you need to use the following instead otherwise your app is crash.
```javascript
 (new Windows.UI.Popups.MessageDialog("Body", "Title")).showAsync().done();
```

I have also created a WP8.1 branch on our Iconic Example repo you can try out to make sure it works for you.
https://github.com/one-signal/OneSignal-Ionic-Example/tree/WP8.1

@Omnem Have you been to pinpoint the build issue you were seeing in your project?

Thanks.

**Comment by Omnem** [comment]
Unfortunately, I've not returned to this yet. Sorry about that. 

Feel free to close it and I will update when I get a chance.

Thank you for this beautiful service, for keeping it free and for continuously updating it. 
Its appreciated.
