### ISSUE TITLE
setLogLevel documentation vs. implementation discrepancy

### ISSUE THREAD

**Issue by mriegler** [one-signal/OneSignal-Cordova-SDK#24]
setLogLevel in the source code expects an object ala

    .setLogLevel({logLevel: 4, visualLevel: 0});

but the documentation states usage as

    .setLogLevel(4, 0);

**Comment by jkasten2** [comment]
Thanks for reporting this, we just updated our documentation page.
https://documentation.onesignal.com/v2.0/docs/phonegap--cordova-sdk-api#section-setloglevel
