### ISSUE TITLE
onesignal-cordova-plugin-pgb-compat doesn't build for iOS with Intel XDK and CLI 5.1.1

### ISSUE THREAD

**Issue by JoeSchr** [one-signal/OneSignal-Cordova-SDK#25]
Hi there,

build log states following:
```
Plugins/onesignal-cordova-plugin-pgb-compat/OneSignal.m:1050:30: error: property 'alertTitle' not found on object of type 'UILocalNotification *'
                notification.alertTitle = data[@"m"][@"title"];
                             ^
1 error generated.
```

I have to use pgb-plugin because Intel XDK doesn't support cradle. Please advise.

**Comment by jkasten2** [comment]
Hello,

You will need to have Xcode 6.2 or newer installed and activated as the default version.

Thanks.

**Comment by jkasten2** [comment]
Feel free to re-open the thread if this did not fix your issue.

Thanks.
