### ISSUE TITLE
How to use my custom backend id so i know whom to send the notification?

### ISSUE THREAD

**Issue by softBarbarian** [one-signal/OneSignal-Cordova-SDK#26]
How to use my custom backend id so i know whom to send the notification? do you reccomend just tagging every user with user_id = iajdhgfkl tag?

**Comment by roblav96** [comment]
what you want to do is attach the users id when they login. for example:

on device ready:
```javascript
	window.plugins.OneSignal.getIds( function ( ids ) {
		$scope.oneSigID = ids.userId
	} )
```

then during login post that id as a parameter and keep it in your backend:
```javascript
{
"dname":  "Robert Laverty" ,
"id":  "roblav96" ,
"oneSigID":  "56649d8f-64c6-4740-6784-434339e372bd" ,
"pass":  "8f085c893e15d8e56065f47bb5c98b12f57cef3866ab3569eefd326ed65080c1" 
}
```

**Comment by softBarbarian** [comment]
Thanks for the reply @roblav96
