### ISSUE TITLE
How to disable creating notifications completely?

### ISSUE THREAD

**Issue by roblav96** [one-signal/OneSignal-Cordova-SDK#27]
For security purposes, I don't want the cordova client to be able to create notifications. I only create them on my backend using the REST API. How can I achieve this?

I might be overthinking it, because the user would need the other users id, but just in case :D

**Comment by jkasten2** [comment]
Sorry about the delay, I'll discuss this with our team next week and will get back to you.

Thanks.

**Comment by roblav96** [comment]
No worries at all! Thank you!!!

**Comment by jkasten2** [comment]
A REST API key is needed for all targeting parameters except for include_player_ids. However we don't consider this a security issue has the playerId/userId is a randomly generated UUID isn't statistically guessable with brute force.

Thanks.
