### ISSUE TITLE
Android App Badge number Support

### ISSUE THREAD

**Issue by bottasergio** [one-signal/OneSignal-Cordova-SDK#29]
Is it possible to know when a notification arrives and fire some event? Even when the user does not open the notification? I use Phonegap Build I will really appreciate if there is some way to do that without having to develop in Java. Thanks

**Comment by jkasten2** [comment]
Hello,

I haven't looked too deep into Cordova / PhoneGap if it is possible to initialize it without opening the main Android Activity itself. However if it were possible due to the start up of the runtime we will most likely opt to for go this feature and require to use native Java  or Objective-c / Swift to do this.

However what is your use case? Would an option to get all unopened notifications when the app starts meet your needs?

Thanks.

**Comment by bottasergio** [comment]
I   want to  increase the badge number on Android (using another plugin)

**Comment by jkasten2** [comment]
I see, we have gotten a few requests for setting a badge number so we will be looking into adding support for it in a future update.

Would simply setting the badge number to the number of displayed notifications work for you or you looking to do something more custom?

Thanks.

**Comment by bottasergio** [comment]
Just increase the badge  number.  Even when app is not active .
And of course some method to decrease it when notification is  read or app is opened. 
 Thanks

**Comment by roblav96** [comment]
This would be awesome!

**Comment by jkasten2** [comment]
@bottasergio @roblav96 Android badge counts are now automatically enabled the latest version of our plugin. See these release notes.
https://github.com/one-signal/OneSignal-Cordova-SDK/releases/tag/1.12.0

Note: Make sure to use latest version (1.12.1) to prevent build error introduced in 1.12.0.

**Comment by roblav96** [comment]
@jkasten2 Thanks so much! This is great!!!

**Comment by bottasergio** [comment]
@jkasten2 Excellent!

**Comment by AcademyLime** [comment]
This feature is great but you should know that enabling it automatically causes some issues in the process of migration. I will explain:

1. Assume that I published an updated version with OneSignal and migrated all user tokens from the old platform (Pushbots).
2. I started using OneSignal API. So all installed versions (updated or old using Pushbots) are receiving push via OneSignal.
3. However, the old versions on Android receives notifications with "1" as the notification body, while the updated versions are just fine.

I cannot (should not) force every device to update. So until every android device is updated to the new build with OneSignal, they will see a silly "1" string as the notification body. 

Any suggestions? 

I will have to postpone migration to OneSignal until the android badge could be enabled or disabled manually through API.

**Comment by jkasten2** [comment]
@AcademyLime Bages values set completely client side by our SDK, no changes were may to our GCM payload to support them. The "1" showing up in the old version of your app must be from another property. I am guessing the Pushbots SDK isn't checking to see if the payload is in their format before processing it.

You can use the app version filter in the Segments page to target users who have updated to a version of your app with OneSignal in it. You can contact OneSignal support while signed in to the dashboard with the button on the bottom right if you are having issues getting the filters to work.

**Comment by diegolmello** [comment]
This should be more like ios_badgeType and ios_badgeCount.
