### ISSUE TITLE
Windows Phone support and Notification TTL

### ISSUE THREAD

**Issue by vespino** [one-signal/OneSignal-Cordova-SDK#3]
2 improvements for this service:

- Windows Phone support
- Expiration time; Set the period after which the push won't be delivered if the device was offline.

Keep up the good work!

**Comment by jkasten2** [comment]
* Windows Phone support - Adding WP support to this Cordova plugin is on our roadmap.
* Expiration time - This is not related to client code, however, it is a server feature we will consider adding in the future.

Thanks for the feedback.

**Comment by jkasten2** [comment]
We just added support for Windows Phone 8.1 (WP8.1) in our latest 1.9.0 update. This will work with all Cordova forks that support WP8.1 as a platform which is believe is all the major ones except Adobe's PhoneGap Build (PGB).

Thanks.

**Comment by vespino** [comment]
When can we expect support for PGB?

**Comment by jkasten2** [comment]
PGB does not support Windows Phone 8.1 builds yet. I recommend adding the the following phongap/build [repo issue](https://github.com/phonegap/build/issues/409) and voting on the [PhoneGap Build thread](http://community.phonegap.com/nitobi/topics/windows-phone-8-1-not-being-built).

Thanks.

**Comment by vespino** [comment]
And what about WP8.0?

**Comment by jkasten2** [comment]
We do not plan on bring support for WP8.0 projects as this requires a whole wrapper/proxy of its own. PGB is the only fork of Cordova I know that does not support WP81 projects and I can't see why they wouldn't add support for it in the future.

**Comment by jkasten2** [comment]
'ttl' (Time To Live) has been added to the OneSignal Create Notification REST API.
https://documentation.onesignal.com/docs/notifications-create-notification
