### ISSUE TITLE
notificationOpenedCallback App in background

### ISSUE THREAD

**Issue by paulohenriqu** [one-signal/OneSignal-Cordova-SDK#31]
Hello.

When app is in background (via home button) and a notification is received the notificationOpenedCallback is triggered as expected.

But when app is in background via back button, the notification is received, appears at the notification area, but when tapped the  notificationOpenedCallback is not triggered.

**Comment by jkasten2** [comment]
Hello,

The [notificationOpenedCallback](https://documentation.onesignal.com/docs/phonegap--cordova-sdk-api#section-notificationopenedcallback) should only fires in the following 2 cases.
* The user taps on a notification.
* A notification is received when the app is currently in focus.

After pressing the home button can you wait a few seconds before sending a notification. This will make sure that the app is being recognized as backgrounded by our SDK.

There was some back button issues on an older version of our SDK on Android devices. Can you verify your using 1.10.0 or newer of our SDK by running `cordova plugin list`.

Lastly what version of Android are you testing on?

Thanks.

**Comment by paulohenriqu** [comment]
Hi, thanks for answering so quickly.

After pressing the home button everything works fine. But if i leave the application pressing the back button on the last view (I believe Android will call onDestroy()) I'm able to receive the notification, but when I tap the notification  the notificationOpenedCallback function is not fired.

I'm using the version 1.10.1 and testing on Android 5.1.1

**Comment by jkasten2** [comment]
See, thanks for the information. Do you have the same issue when you swipe the app away from the Recent Apps list then tap on the notification? Are you calling OneSignal.init in your code the navigating to a different page in your app as it starts up?

If you can provide a simple example project reproducing the issue this will help us get a fix turned around quickly.

**Comment by paulohenriqu** [comment]
Yes, I have the same issue when I swipe the app away from the Recent Apps list.

I'm calling OneSignal.init inside  $ionicPlatform.ready

I'm working with a modification of that repo: https://github.com/one-signal/OneSignal-Ionic-Example/
The example shows the same issue, the alert won't open if the app is closed with the back button.

**Comment by paulohenriqu** [comment]
Hi,
Just to let you know, I also tested it with iOS devices, Even if I turn it off and on again the callback function works.
 The issue is only with Android devices

**Comment by jkasten2** [comment]
@paulohenriqu Thanks for the detailed information, I have fixed the regression issue in 1.10.2 of our SDK. Let us know if you continue seeing issues on this version.

**Comment by paulohenriqu** [comment]
It works perfectly now.
Thanks!

**Comment by mindr242** [comment]
I'm having this issue again. When app is in background and notification received and then clicked, the app state refreshes, but it the callback is not called.

**Comment by ezazwar1** [comment]
i am also facing same issue , On ios it is working fine but on android it doesnt seem to be working at all

**Comment by jkasten2** [comment]
@mindr242 @ezazwar1 Can you make sure OneSignal init is called each time your page loads? This will ensure the callback current.

**Comment by ezazwar1** [comment]
yep the init method is called

**Comment by Slavezax** [comment]
Same issue here. I have an index.html which redirects users to main.html based on the local storage data. If app is closed, and if I notification comes, this function is not triggering.
