### ISSUE TITLE
Ionic-Cordova fails to find OneSignal plugin in the app

### ISSUE THREAD

**Issue by NutBoltu** [one-signal/OneSignal-Cordova-SDK#34]
I am using cordova 6.0.0 and cordova-platform-android 6.0.0 for developing my ionic app.
I have added the one signal plugin in initialization scripts. The scripts looks like below.
```
sudo cordova platform add ios
sudo cordova platform add android
sudo ionic resources

sudo cordova plugin add onesignal-cordova-plugin
sudo cordova plugin add cordova-plugin-crosswalk-webview
sudo cordova plugin add ionic-plugin-keyboard
sudo cordova plugin add cordova-plugin-whitelist
sudo cordova plugin add cordova-plugin-console
sudo cordova plugin add cordova-plugin-splashscreen
sudo cordova plugin add cordova-plugin-network-information
sudo cordova plugin add cordova-plugin-screen-orientation
sudo cordova plugin add cordova-plugin-inappbrowser
sudo cordova plugin add https://github.com/katzer/cordova-plugin-local-notifications.git
sudo cordova plugin add cordova-plugin-vibration
sudo cordova plugin add https://github.com/VersoSolutions/CordovaClipboard.git
```

and in my ionic app in the app.js file I call the OneSignal init method as below.
```
ionic.Platform.ready(function () {
    app.run(function () {

        var notificationOpenedCallback = function(jsonData) {
            //console.log('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
        };
       console.log('oneSignal plugin', window.cordova.plugins.OneSignal);
        window.cordova.plugins.OneSignal.init("my-one-signal-app-id",
            {googleProjectNumber: "my-google-app-id"},
            notificationOpenedCallback);

        window.cordova.plugins.OneSignal.enableInAppAlertNotification(true);
        

    });
});
```
But when I run the app it displays as below
```
oneSignal plugin undefined
app.js:29 Uncaught TypeError: Cannot read property 'init' of undefined

```
Is it an issue with cordova 6.0.0?

**Comment by jkasten2** [comment]
Can you check the adb logcat for any errors or warnings before this one?

I tested our [OneSignal-Ionic-Example](https://github.com/one-signal/OneSignal-Ionic-Example) with Cordova 6.0.0 without any issues. Does this build and run ok for you on an Android device?

Thanks.

**Comment by NutBoltu** [comment]
I have found 2 errors.
1. Instead of using window.cordova.plugins I have to use window.plugins
2. In my app a service overwrite the plugins. So it shows OneSignal undefined.
And I works for cordova 6.0.0 and cordova platform android 6.0.0.
Closing issue.

**Comment by jkasten2** [comment]
Good to hear you got it working.

1. Ah yes, sorry overlooked that.
2. Was there any other plugin overwriting the window.plugins variable or was it just something in your app's code?

Thanks.

**Comment by NutBoltu** [comment]
@jkasten2 
2. It was my app service which overwrite the plugins not any other plugin.
 Thanks .
