### ISSUE TITLE
Google service dependencies version

### ISSUE THREAD

**Issue by Rmannn** [one-signal/OneSignal-Cordova-SDK#36]
Today you are adding deps in gradle with the "+" version.
This create a problem supporting with cordova and the default google service sdk.
Adding classpath 'com.google.gms:google-services:+' does not help.

**Comment by jkasten2** [comment]
I don't believe there is a default Google Play services SDK included with Cordova. Could you let us know what other plugin your using that is creating the conflict?

**Comment by Rmannn** [comment]
Following lines
```
compile "com.google.android.gms:play-services-gcm:+"
compile "com.google.android.gms:play-services-analytics:+"
compile "com.google.android.gms:play-services-location:+"
```
seem to not be compatible with 
```
apply plugin: 'com.google.gms.google-services'
```

This result into an error.
```
Execution failed for task ':processDebugGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 8.3.0.
```

**Comment by jkasten2** [comment]
Thanks for the information. Is `apply plugin: 'com.google.gms.google-services'` from your platforms/android/build.gradle file?

I haven't seen this added to a gradle file before by Cordova. Did you add this to your file or do you know  the plugin that did? If your not sure you can send us a list of plugins your using by running `cordova plugin list`.

Thanks.

**Comment by Rmannn** [comment]
You're welcome, this plugin is amazing! 
Yes I added the deps by my self.
Let me explain.

I followed all the steps to configure the cordova plugin. It's working on iOS with success.
Then I tried to deploy my app on Android following the steps.

But, the device ready event was never fired. (5 seconds delay)
After some debug using logcat, i found this error
```
GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
03-03 20:27:31.360  3546  3546 E GMPM    : Scheduler not set. Not logging error/warn.
03-03 20:27:31.380  3546  3563 E GMPM    : Uploading is not possible. App measurement disabled
```
Even after adding the google-services.json into the android/ folder, errors was still here.
This is my initial error. 

Maybe I am totally wrong about this bug.

**Comment by jkasten2** [comment]
You can safely ignore those warnings, you don't need to create a `google-services.json` file as our SDK does not use this to register with GCM for push notifications.

The Cordova `deviceready` event isn't firing at all for you? This sounds like a different issue with your project. Keep looking through the logcat for other errors / warning from your app. You can send an email to support@onesignal.com or open the red chat bubble and send us the full logcat and we can take a look.

Thanks.

**Comment by Rmannn** [comment]
Yes you re right, my bad... The device block the device ready cause to a script in the index.html returning a 404... Sorry for this.
