### ISSUE TITLE
notificationOpenedCallback not being called on First Run of the app after Install

### ISSUE THREAD

**Issue by codecrab-studios** [one-signal/OneSignal-Cordova-SDK#39]
We Created an Apk file to install on Device, Installed and Device Registered with OneSignal perfectly, starts recieving pushes.  Now in the Push we sent some additonal Data, but when we hit the push notification and it takes us to App, but  "notificationOpenedCallback"  is not called up....

But then we tried something, We closed the app and reopened it, Resent the Push with Additional Data, and now the "notificationOpenedCallback"  worked without any issues

We are using Ionic Framework and Cordova.

**Comment by jkasten2** [comment]
Hello,

If you have a multiple page can you try calling OneSignal init in each to see if it fixes your callback issue?

Thanks.

**Comment by jkasten2** [comment]
@codecrab-studios Are you still running into this issue? Feel free to reopen this issue and reply if you're still stuck.
