### ISSUE TITLE
The method removeNotificationOpenedHandler() is undefined for the type OneSignal

### ISSUE THREAD

**Issue by jordan-enev** [one-signal/OneSignal-Cordova-SDK#42]
Hello,

I tried to run a Cordova app with OneSignal plugin, but it fails with the following error at void com.plugin.gcm.OneSignalPush.onDestroy():287:
`The method removeNotificationOpenedHandler() is undefined for the type OneSignal`

I checked it on Eclipse and Android Studio - and the error exists on the both platforms.

The version of OneSignal is:
`onesignal-cordova-plugin 1.11.2 "OneSignal Push Notifications"`

Also when I comment out the 287 line of code - it works:
`@Override
  public void onDestroy() {
      // OneSignal.removeNotificationOpenedHandler();
}`

BTW I tried with older version of the plugin (1.10.1) and it works.

**Comment by jkasten2** [comment]
It seems that the copy of the `onesignal-cordova-plugin` only got partially updated. It sounds like an older version of the `plugin.xml` or `onesignal.aar` file is being used on your system.

Can you try following our [Clean Build](https://documentation.onesignal.com/docs/cordova-common-problems#clean-build) instructions?

Thanks.

**Comment by jordan-enev** [comment]
Thank you for the answer.

I've tried a clear build with the following commands, but unfortunately the problem still exists:
1. cordova plugin remove onesignal-cordova-plugin
2. cordova platform remove android
3. cordova platform add android
4. cordova plugin add onesignal-cordova-plugin

I forgot to say that I'm on Windows.

**Comment by jkasten2** [comment]
@jordan-enev Can you try to add `rm -rf platforms/android` after step 2 in your test case?

Do you see the same issue if you create a new project and add our plugin.

Does it build correctly with `cordova build android` instead of using Android Studio or Eclipse?

Also note we just released version 1.12.1 of our plugin.

**Comment by jkasten2** [comment]
@jordan-enev Were you able to get things working? Feel free to reopen this issue if you're still stuck.

**Comment by jordan-enev** [comment]
I've updated to onesignal-cordova-plugin **1.12.4** "OneSignal Push Notifications" and the problem disappears:
`The method removeNotificationOpenedHandler() is undefined for the type OneSignal`

--- 
But now there is a similar problem at line 258 in the same file:
`The method setEmail(String) is undefined for the type OneSignal`

When I comment out the following - then I can run my project:
```
//      try {
//        OneSignal.setEmail(data.getString(0));
//      } catch(Throwable t) {
//        t.printStackTrace();
//      }
```
I tried to build it via console, but it fails on the following task:
>  failed for task ':mergeDebugResources'.

---
Also I downloaded [Cordova Hello world example](https://github.com/apache/cordova-app-hello-world) and added onesignal-cordova-plugin **1.12.4**. The same problem as above:
`The method setEmail(String) is undefined for the type OneSignal`

It is interesting that I succeed to build it via console, but in Eclipse it doesn't work (maybe there are more validations).

**Comment by jkasten2** [comment]
@jordan-enev Sorry about the delay, we haven't had any other reports of this issue but good to hear you found a work around.

Eclipse / ANT isn't support by Google any more so I recommend updating to Android Studio / Gradle  in the future.
