### ISSUE TITLE
[iOS & Android] Build Fail Errors

### ISSUE THREAD

**Issue by roblav96** [one-signal/OneSignal-Cordova-SDK#44]
Just updated your latest release.

# iOS
![screen shot 2016-04-01 at 10 55 43 pm](https://cloud.githubusercontent.com/assets/1457327/14224067/f4613146-f85c-11e5-9e3b-e3eb1301a8a6.png)

# Android
![screen shot 2016-04-01 at 10 56 46 pm](https://cloud.githubusercontent.com/assets/1457327/14224070/0c2ad46c-f85d-11e5-81fd-2f3b1d47425b.png)

Thank you for all your hard work!

**Comment by roblav96** [comment]
Any why does a push notification service need access to my users locations???

**Comment by jkasten2** [comment]
@roblav96 Thanks for reporting the build errors. Just fixed both of these in version 1.12.1 of our plugin.

The location code is for our geotagging feature. It is a filter found on our Dashboard under Segments called "Location Radius".

**Comment by roblav96** [comment]
@jkasten2 Ah that's really cool! Any documentation on this new feature?

**Comment by jkasten2** [comment]
I'll be creating some documentation on our main setup guide soon. Until then you follow this outline.

1. App Permissions
   * iOS - plist entries
       - iOS 6 and 7 - `NSLocationUsageDescription`
       - iOS 8+ - `NSLocationWhenInUseUsageDescription`
  * Android - `AndroidManifest.xml` permissions
     * `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`
     * OR
     * `<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>`

2. Both platforms prompt user
Run `window.plugins.OneSignal.promptLocation();` anytime after `OneSignal.int` to prompt the user.

**Comment by roblav96** [comment]
@jkasten2 That's more than enough to get me up and running! Thanks!!!
