### ISSUE TITLE
Disable notifications

### ISSUE THREAD

**Issue by BugsBunnyBR** [one-signal/OneSignal-Cordova-SDK#47]
Hi, is it possible to make available a method to disable the push notifications? I would like to give to my users a settings to enable/disable it.

**Comment by jkasten2** [comment]
@BugsBunnyBR You can use [setSubscription](https://documentation.onesignal.com/docs/phonegap--cordova-sdk-api#setSubscription) to enable / disable OneSignal notifications.

**Comment by BugsBunnyBR** [comment]
Is it possible to know if the notifications are enabled or not?

**Comment by Link184** [comment]
Give me a way how to check state of subscrubation

**Comment by jkasten2** [comment]
@BugsBunnyBR @Link184 [getIds](https://documentation.onesignal.com/docs/cordova-api-reference#getIds) can be called get the pushToken. If it null the then user will not be able to receive notifications. This accounts for the user disabling notification as well on iOS.

**Comment by sonicwong** [comment]
@BugsBunnyBR 
You can run `window.plugins.OneSignal.setSubscription(false);` after plugin init.

**Comment by sonicwong** [comment]
@jkasten2 
I set setSubscription to false,
go web ui saw user is "User Opted Out".
then call "getIds" again, it return pushToken (not null) to me.

I am using ionic 1.3 with latest xcode version8.2.1.

**Comment by Anushahrithi** [comment]
Do you have any sample code for that.if yes can u please provide me
