### ISSUE TITLE
IOS Background Notifications

### ISSUE THREAD

**Issue by wrannaman** [one-signal/OneSignal-Cordova-SDK#50]
When I create a message on the site and the app is not open ( not even in the background ) I receive the push. The message created from the site has the content_availble set to false. 

When I create a message from my own server and the app is open or in the background, everything works as expected, but when the app is closed, the notification does not show up. 

I have tried
- "content_available": 1
- "content_available": true
- not putting in the content_available parameter. 

My full payload looks like

{
        "app_id": "...",
        "contents": { "en": "..."},
        "include_player_ids":["..."],
        "ios_sound": "yak.wav",
        "android_sound": "yak.wav",
        "ios_badgeType": "SetTo",
        "ios_badgeCount": Number(badgeCount),
        "buttons": [ {"id": "view", "text": "View", "icon": "ic_menu_share"} ],
        "data": { "path": path},
        //"content_available": 1,
        //"_background_data":true,
}

My plugins are
com-badrit-base64 0.2.0 "Base64"
com.cmackay.plugins.googleanalytics 0.1.22 "GoogleAnalytics"
com.phonegap.plugins.PushPlugin 2.5.0 "PushPlugin"
cordova-plugin-actionsheet 2.2.2 "ActionSheet"
cordova-plugin-app-event 1.2.0 "Application Events"
cordova-plugin-badge 0.7.2 "Badges"
cordova-plugin-camera 2.2.0 "Camera"
cordova-plugin-compat 1.0.0 "Compat"
cordova-plugin-console 1.0.3 "Console"
cordova-plugin-device 1.1.2 "Device"
cordova-plugin-facebook4 1.7.0 "Facebook Connect"
cordova-plugin-file 4.2.0 "File"
cordova-plugin-file-transfer 1.5.1 "File Transfer"
cordova-plugin-geolocation 2.2.0 "Geolocation"
cordova-plugin-inappbrowser 1.4.0 "InAppBrowser"
cordova-plugin-splashscreen 3.2.2 "Splashscreen"
cordova-plugin-statusbar 2.1.3 "StatusBar"
cordova-plugin-whitelist 1.2.2 "Whitelist"
cordova-plugin-x-socialsharing 5.0.12 "SocialSharing"
de.appplant.cordova.plugin.badge 0.7.1 "Cordova Badge Plugin"
ionic-plugin-deploy 0.5.0 "IonicDeploy"
ionic-plugin-keyboard 2.0.1 "Keyboard"
onesignal-cordova-plugin 1.12.3 "OneSignal Push Notifications"
org.transistorsoft.cordova.background-notification 0.1.0 "CDVBackgroundNotification"
phonegap-plugin-push 1.6.2 "PushPlugin"

I'm using ionic 1.7.14 and xcode 7.3 with a deploy target of 8.0

any guidance would be appreciated! Thanks!

**Comment by jkasten2** [comment]
The OneSignal Action Buttons have some special requires as its uses content-available 1 to create custom categories on the fly.

See the requirements in our documentation.
[5. iOS notifications with action buttons not displaying](https://documentation.onesignal.com/docs/common-problems#5-ios-notifications-with-action-buttons-not-displa)
```
In order for notifications with buttons to display the following must be true:

You can not force close the app by double tapping the home button and swiping away your app.
Go to Settings>General>"Background App Refresh" and mke sure it is enable for both the device and your app.

Make sure "Remote notifications" are checked under Capabilities>Background Modes shown in step 2. Add Required Capabilities.
```

**Comment by neves** [comment]
Can you receive notification while in background?
I can't make it work with OneSignal, just with this other one:
https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m#L112

**Comment by wrannaman** [comment]
@neves This is working for me in the background, foreground, and after force quitting the app:

Client:
      `window.plugins.OneSignal.enableSound(true);`
      `window.plugins.OneSignal.enableVibrate(true);`
      `window.plugins.OneSignal.init("xxx", {googleProjectNumber: "yyyy"},function(a,b,c){`
       ` if (a.additionalData.path)`
       ` {`
          `$location.path('/feed/notifications');`
        `}`
      `});`
      `window.plugins.OneSignal.getIds(function(ids) {`
       ` User.savePushAndDevice( ids.pushToken, ids.userId);`
      `});`
     ` window.plugins.OneSignal.enableInAppAlertNotification(true);`

Server:
   sendPush: function( push, note ){

    return new Promise(function(resolve,reject){
    
		var http 	      = require('https');
		var pushTokens  = [push.deviceId];
		var options = {
			host: "onesignal.com",
			path: "/api/v1/notifications",
			method: "POST",
      port: 443,
			headers: {
				"Content-Type": "application/json",
				"X-Ionic-Application-Id":  "xxx",
				"Authorization": "basic " + "xxx"
			}
		};
    
    PushNotification.findOne({pushToken: push.pushToken})
    .then(function(thisPush){
      var badgeCount = typeof(thisPush) != 'undefined' && typeof(thisPush.badgeCount) != 'undefined' ? Number( thisPush.badgeCount ) : 0;
      badgeCount++;
      var data = {
        "app_id": "xxx",
        "contents": { "en": note.description },
        "include_player_ids": pushTokens,
        "ios_sound": "yak.wav",
        "android_sound": "yak.wav",
        "ios_badgeType": "SetTo",
        "ios_badgeCount": Number(badgeCount),
        "data": { "path":'/feed'},
      }

      data = JSON.stringify( data );

      var newReq = http.request(options, function(pushStatus){
    		var body = "";
    		pushStatus.on('data', function(d) {
    			body  +=  d.toString('utf8');
    		});
    		pushStatus.on('end', function() {
          PushNotification.update({pushToken: push.pushToken}, { badgeCount: badgeCount})
          .then(function(updated){
           return resolve(body);
          })
          .catch(function(err){
           return resolve(body);
          })
    		});
  		});
  		newReq.write( data );
  		newReq.end();
    })
     .catch(function(err){
       return resolve({error: err});
     });
  });
   },

**Comment by wrannaman** [comment]
@neves  yes, I understand. No, not if the notification is not clicked on, and as I understand it, this is the expected behavior on ios. I believe you can do more interesting background processing on android.

**Comment by neves** [comment]
@wrannaman That's the point, ios do support this, phonegap-plugin-push has it implemented, I tested and it really works!
This is the code:
https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m#L112

**Comment by scorpnode** [comment]
Is this fixed for onesignal?

**Comment by elysiopires** [comment]
Does this already works? I Need to open a notification over my closed app and process additional data to redirect the user to a specific feature.
