### ISSUE TITLE
raw alert message showing in push notification

### ISSUE THREAD

**Issue by ahsan154** [one-signal/OneSignal-Cordova-SDK#53]
hi experts, i had this issue nd i am unable to find it online , i am getting this alert, and i don't this to appear but i dont know from where it is coming, i had same issue in both ios and android....

any help in this regard will be really appreciated...

let me share my javascript code as well that i got from your documentation

document.addEventListener('deviceready', function () {

// Enable to debug issues.
// window.plugins.OneSignal.setLogLevel({logLevel: 4, visualLevel: 4});
myApp.showIndicator();
var notificationOpenedCallback = function (jsonData) {
    //alert('didReceiveRemoteNotificationCallBack: ' + JSON.stringify(jsonData));
    window.location = 'dashboard.html';
};

window.plugins.OneSignal.init("myonesingnalid",
        {googleProjectNumber: "my google project number"},
        notificationOpenedCallback);

window.plugins.OneSignal.getIds(function (ids) {

    localStorage.setItem('player_id', ids.userId);
    myApp.hideIndicator();

});

// Show an alert box if a notification comes in when the user is in your app.
window.plugins.OneSignal.enableInAppAlertNotification(false);

}, false);
![bug](https://cloud.githubusercontent.com/assets/12672971/15177625/6e4db1c2-178a-11e6-992b-f7eebddd8f08.PNG)

**Comment by jkasten2** [comment]
The alert in your screenshot is from our example code. I see you have the alert commented out in the above code. Can you make sure your app got rebuilt correctly and you don't have another copy of this code somewhere else your app?

**Comment by jkasten2** [comment]
Closing this issue, please feel free to re-open if you're stilling having this issue.
