### ISSUE TITLE
Support for purchases

### ISSUE THREAD

**Issue by anonrig** [one-signal/OneSignal-Cordova-SDK#57]
Support for purchases will be very much appreciated.

I am looking for a way to implement free users & paid users segmentation while using onesignal cordova sdk, and unable to do so.

Thanks.

**Comment by jkasten2** [comment]
In app purchases (IAP) are automatically tracked by our SDK for you on iOS and Android. Let us know if your test purchases are not showing up.

**Comment by anonrig** [comment]
Thank you for your reply. I am using cordova in app purchase plugin for IAP, and couldn't see any data related to that on OneSignal.

**Comment by jkasten2** [comment]
Can you contact OneSignal support from the red help buble in the bottom right of our dashboard? We can check your account to see if we are getting any events. Let us know if you currently test with Android or iOS.

Thanks.
