### ISSUE TITLE
Amazon Messaging Gracefully Degrade if ADM Is Unavailable

### ISSUE THREAD

**Issue by northkode** [one-signal/OneSignal-Cordova-SDK#58]
I dont see you guys handling this. The manifest file has 
amazon:enable-feature android:name="com.amazon.device.messaging" android:required="false" /

but i dont see anywhere, where you might be checking if amd is not present then degrad without dying.

**Comment by jkasten2** [comment]
@northkode This is handled from OSUtils.getDeviceType() in the native Java code used by this plugin.
https://github.com/one-signal/OneSignal-Android-SDK/blob/master/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSUtils.java#L42

Feel free to reopen this issue if you're seeing an problem with the not working in your app.
