### ISSUE TITLE
Android phonegap Build failed on build.phonegap.com

### ISSUE THREAD

**Issue by elbidone** [one-signal/OneSignal-Cordova-SDK#59]
Hi,

I've tested to build App (cli-6.1.0) with one-signal cordova plugin but raised following issue:
The iOS build seems to work, I didn't test the install yet.

```bash
:prepareComAndroidSupportSupportV42300Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics840Library
:prepareComGoogleAndroidGmsPlayServicesBase840Library
:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:prepareComGoogleAndroidGmsPlayServicesGcm840Library
:prepareComGoogleAndroidGmsPlayServicesLocation840Library
:prepareComGoogleAndroidGmsPlayServicesMaps840Library
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library
:prepareComOnesignalOneSignal241Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaWithJavacNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:compileDebugNdk UP-TO-DATE
:compileDebugSources
:transformClassesWithDexForDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/analytics/internal/Command$1;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)


 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.101.x86_64/bin/java'' finished with non-zero exit value 2
```

**Comment by jkasten2** [comment]
It looks like you have 2 plugins that are including different versions of the "Google Play services" library. See the [OneSignal Cordova Troubleshooting](https://documentation.onesignal.com/docs/cordova-common-problems) section for a list of plugins are known to cause compbitlity issues and how to fix them.

If you're still seeing an issue add the full output from running the following as a new comment.
```
cordova plugin list
```

**Comment by elbidone** [comment]
I've removed "com.adobe.plugins.gaplugin" as recommended on troubleshooting and it works fine, tks!!

**Comment by surgianto** [comment]
Build Date: 2017-09-04 13:51:44 +0000
--------------------------------------------------------------------------------
PLUGIN OUTPUT
--------------------------------------------------------------------------------
Fetching plugin "cordova-plugin-crosswalk-webview@1.8.0" via npm
Installing "cordova-plugin-crosswalk-webview" at "1.8.0" for android
Fetching plugin "cordova-plugin-legacy-whitelist@1.1.1" via npm
Installing "cordova-plugin-legacy-whitelist" at "1.1.1" for android
--------------------------------------------------------------------------------
COMPILE OUTPUT
--------------------------------------------------------------------------------
Configuration on demand is an incubating feature.
null
org.xwalk:xwalk_core_library:19+

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'project'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not resolve org.xwalk:xwalk_core_library:19+.
     Required by:
         :project:unspecified
      > Could not resolve org.xwalk:xwalk_core_library:19+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
               > Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.634 secs
undefined

please help me

**Comment by jkasten2** [comment]
@surgianto OneSignal does not use the crosswalk library and I don't see OneSignal in your build log. I recommend checking the repo of this plugin for debugging your issue.
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview
