### ISSUE TITLE
cordova build ios failed

### ISSUE THREAD

**Issue by SeVeNDuS** [one-signal/OneSignal-Cordova-SDK#6]
Hi,
I am trying to install one signal into my app and failed into iOS platform, all is perfect in Android one.

I got the following error:
com.onesignal.plugins.onesignal/OneSignal.m:1045:30: error: 
      property 'alertTitle' not found on object of type 'UILocalNotification *'
                notification.alertTitle = data[@"m"][@"title"];

And after that the command told me that the build is failed

Thanks!

**Comment by jkasten2** [comment]
Hello,

What version of Xcode do you have activated? You will need to be using Xcode 6.2 or later to build your app with the latest version of our plugin.

Thanks.

**Comment by SeVeNDuS** [comment]
I realized after write this issue. I am upgrading my OSX and my XCODE.

Thanks for the suport
