### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by Leftyx** [one-signal/OneSignal-Cordova-SDK#7]
I couldn't update my oneSignal plugin cause of a build failure so I decided to create a fresh new project using ionic.
This is the error I get:

![onesignal](https://cloud.githubusercontent.com/assets/171024/9328246/f4a09e2e-459e-11e5-9367-3eb7a7c35b1f.png)

Using the Android 5.1.1 (API 22)

**Installed** Google Play Services
**Installed** Google Repository
**Installed** Android Support Repository
**Installed** Android Support Library

**Cordova CLI**: 5.2.0
**OS**: Windows 7 SP1
**Node Version**: v0.12.7
**Android Engine**: 4.1.1

**Comment by jkasten2** [comment]
Hello we just deployed version 1.8.1 to fix this issue. Follow our [clean build](http://documentation.onesignal.com/docs/cordova-common-problems#clean-build) instructions to get the latest version and so the gradle project settings get cleared.

Thanks.

**Comment by Leftyx** [comment]
Great. It works again. Thanks.
