### ISSUE TITLE
Plugin "onesignal-cordova-plugin" is not present in the project

### ISSUE THREAD

**Issue by Leftyx** [one-signal/OneSignal-Cordova-SDK#8]
I've added the plugin as suggested in the [docs](http://documentation.onesignal.com/v2.0/docs/phonegap-sdk-installation).
and I have the plugin installed in my folder.

When I try to remove it I get this weird message:

```
E:\TEMP\Ionic\pusheroo>cordova plugin rm onesignal-cordova-plugin --save
Plugin "onesignal-cordova-plugin" is not present in the project. Converting value to "com.onesignal.plugins.onesignal" and trying again.
Uninstalling com.onesignal.plugins.onesignal from android
Removing "com.onesignal.plugins.onesignal"
config.xml entry for com.onesignal.plugins.onesignal is removed
```

The plugin gets removed at the end.

**Comment by jkasten2** [comment]
The message is a bit confusing but I can confirm it does remove the plugin. We will look into fixing the message in a future update.

Thanks.
